### ISSUE TITLE
Pipeline test file generation escapes special characters in golden files generation

### ISSUE THREAD

**Issue by P1llus** [elastic/elastic-package#320] opened 2021-04-13 08:57 UTC
When creating new expected.json files from raw log files, it seems that certain characters are HTML escaped, adding in unicode characters in the generated output.

I would like to know is this is the intended results, as it differs from how the output looked like in beat modules test file generation (which used python).

An example would be zeek logs, here characters like `<>` is turned into ` \u003c` and `\u003e`.

Which would turn this example raw event:

```
        "zeek.session_id": "CPRLCB4eWHdjP852Bk",
        "zeek.sip.call_id": "8694cd7e-976e4fc3-d76f6e38@172.16.133.19",
        "zeek.sip.request.body_length": 0,
        "zeek.sip.request.from": "\"AppNeta\" <sip:116954_Boston6@newyork.voip.ms>",
        "zeek.sip.request.path": [
            "SIP/2.0/UDP 172.16.133.19:5060"
        ],
        "zeek.sip.request.to": "<sip:116954_Boston6@newyork.voip.ms>",
        "zeek.sip.response.body_length": 0,
        "zeek.sip.response.from": "\"AppNeta\" <sip:116954_Boston6@newyork.voip.ms>",
        "zeek.sip.response.path": [
            "SIP/2.0/UDP 172.16.133.19:5060"
        ],
        "zeek.sip.response.to": "<sip:116954_Boston6@newyork.voip.ms>;tag=as023f66a5",
        "zeek.sip.sequence.method": "REGISTER",
        "zeek.sip.sequence.number": "4127",
        "zeek.sip.status.code": 401,
        "zeek.sip.status.msg": "Unauthorized",
        "zeek.sip.transaction_depth": 0,
        "zeek.sip.uri": "sip:newyork.voip.ms:5060",
        "zeek.sip.user_agent": "PolycomSoundStationIP-SSIP_5000-UA/3.2.4.0267"
```

To this:
```
"zeek": {
                "session_id": "CPRLCB4eWHdjP852Bk",
                "sip": {
                    "request": {
                        "path": [
                            "SIP/2.0/UDP 172.16.133.19:5060"
                        ],
                        "from": "\"AppNeta\" \u003csip:116954_Boston6@newyork.voip.ms\u003e",
                        "to": "\u003csip:116954_Boston6@newyork.voip.ms\u003e",
                        "body_length": 0
                    },
                    "sequence": {
                        "method": "REGISTER",
                        "number": "4127"
                    },
                    "response": {
                        "path": [
                            "SIP/2.0/UDP 172.16.133.19:5060"
                        ],
                        "from": "\"AppNeta\" \u003csip:116954_Boston6@newyork.voip.ms\u003e",
                        "to": "\u003csip:116954_Boston6@newyork.voip.ms\u003e;tag=as023f66a5",
                        "body_length": 0
                    },
                    "id": {},
                    "uri": "sip:newyork.voip.ms:5060",
                    "transaction_depth": 0,
                    "user_agent": "PolycomSoundStationIP-SSIP_5000-UA/3.2.4.0267",
                    "call_id": "8694cd7e-976e4fc3-d76f6e38@172.16.133.19",
                    "status": {
                        "msg": "Unauthorized",
                        "code": 401
                    }
                }
            },
```

**Comment by P1llus** [comment] 2021-04-13 09:06
This could be resolved by disabling html escaping using:
https://golang.org/pkg/encoding/json/#Encoder.SetEscapeHTML

Which I guess would need to be set somewhere around here: https://github.com/elastic/elastic-package/blob/003c019620b2889172c86ba281819c1dea4ec59a/internal/testrunner/runners/pipeline/test_result.go#L143

**Comment by mtojek** [comment] 2021-04-13 09:28
Thank for opening this issue, @P1llus .

Is it because of readability, compatibility with Beats or do you see any other concern? It works this way as it's default behavior in Go standard library and I'm not sure if we want to change it (unless we have a good justification). As you mentioned both forms are correct :)

Are you working on migrating tests from Beats to integrations?

**Comment by P1llus** [comment] 2021-04-13 09:34
This is really only because of readability, as long as it won't create any issues when the pipeline tester will try to compare then it's not really an issue for me, I just wanted to make sure it's intended behavior.

Just to mention that the actual output of a beat to ES is not escaped, so the golden files would differentiate from the real implementation that way, but not in a big way.

I am currently in the process of removing all the edge processing and moving them to pipelines, and at the same time I am also adding pipeline test files to all the modules that are missing them, starting with the ones on the list here: https://github.com/elastic/security-team/issues/791

**Comment by P1llus** [comment] 2021-04-13 09:44
If its only a decision if we want to keep it this way or not, then I would like to ping @andrewkroh as well, for me its fine to keep it that way, but if all we need to do is disable the html encoding on the encoder, it's a pretty quick fix, but might need to regenerate some generated files to remove the html encoding from them.

**Comment by mtojek** [comment] 2021-04-13 09:49
I don't have any preference here :) If it's more convenient to disable escaping, I would be for doing it. Let's collect more feedback here.

**Comment by ycombinator** [comment] 2021-04-19 17:08
If its a simple change to disable HTML encoding (which it sounds like it is), I'm +1 for making it to improve readability.

**Comment by andrewkroh** [comment] 2023-09-20 17:50
I think we should make the change. These odd representations are showing up in our docs.

<img width="1503" alt="Screenshot 2023-09-20 at 13 49 23" src="https://github.com/elastic/elastic-package/assets/4565752/fd054475-325e-4d66-9d2f-05c810334f4f">

 `elastic-package format` also needs changed, otherwise it will undo the results of the pipeline test generator.

https://github.com/elastic/elastic-package/blob/43c68bc17cba38514c2b9ed79641f6d21e242309/internal/formatter/json_formatter.go#L21

**Comment by jsoriano** [comment] 2023-09-20 18:03
We can maybe apply this to packages with the next package spec version, this way it should be a small change. I will include it in the current sprint.

**Comment by jsoriano** [comment] 2023-11-15 12:00
Reopening, something seems to be still encoding HTML entities https://github.com/elastic/integrations/pull/8478/files#r1391779070

**Comment by jsoriano** [comment] 2023-11-22 12:03
> Reopening, something seems to be still encoding HTML entities https://github.com/elastic/integrations/pull/8478/files#r1391779070

After some investigation, this was likely caused by an old version of elastic-package, and it is probably not worth fixing this, so I will close this issue.

It was generating test documents with encoded HTML entities. We compare documents on tests "by value", unmarshaling them to maps. Go always decodes HTML entities when decoding JSON strings, so the documents are the same for elastic-package independently of they having these characters encoded or not, so build was valid in both cases, but there were unexpected diffs.

We could try to add a check to avoid the introduction of these unexpected changes, but it may be complex as we cannot rely on json package, and is probably not worth fixing it, because in principle it only affects test documents, and eventually everyone will use versions of elastic package that don't encode HTML entities.

**Closed by jsoriano** 2023-11-22 12:03 UTC
Labels: good first issue, discuss
