### ISSUE TITLE
Dashboard tags get duplicated each time elastic-package export dashboards is used

### ISSUE THREAD

**Issue by MichaelKatsoulis** [elastic/elastic-package#1098] opened 2023-01-18 09:08 UTC
If the user does not specify any tag in the dashboards json then the dashboards belonging to an integration take as default the `integration_name` and `managed` tags. These are added by fleet.

![saved-objects-1](https://user-images.githubusercontent.com/26270880/213125501-889f5689-fdf0-47f6-af44-4f6ff7da85e6.png)

In a normal development process the user would update the dashboards in Kibana and then using `elastic-package export dashboards` would export them locally in order to commit the changes. The updated dashboard json includes then the tags as well.

<img width="1760" alt="tags added" src="https://user-images.githubusercontent.com/26270880/213126349-bc0e21dc-dbe0-4d1e-9486-ff0355fadb82.png">

Then the user would commit and push those updated json files. Next time the dashboards are  uploaded to Kibana as part of the integration installation, they get the tags from the dashboards jsons (returned from elastic package tool), plus the defaults added by Fleet again. So then we have the same tags two times.

![duplicated tags](https://user-images.githubusercontent.com/26270880/213127965-f6554405-4e30-41bd-9456-50db5e78887c.png)

And if we export them again the tool will return the duplicated tags. 

<img width="400" alt="git diff" src="https://user-images.githubusercontent.com/26270880/213128364-4145c9dd-754f-4196-9c4c-fdad56cef332.png">

So next time we upload them we will have 3 times the same tags and so on.

The expected behaviour would be that the `elastic-package` tool would omit adding in json files, those tags that are added by default from fleet. They seem to have an id convention like `kubernetes-fleet-managed-default` and `kubernetes-fleet-pkg-kubernetes-default`

**Comment by jsoriano** [comment] 2023-02-20 15:21
Duplicate of https://github.com/elastic/elastic-package/issues/1060. Thanks for the report and the context!

**Closed by jsoriano** 2023-02-20 15:21 UTC
Labels: bug
