### ISSUE TITLE
Duplicate package entries in elastic-package stack kibana UI

### ISSUE THREAD

**Issue by matschaffer** [elastic/elastic-package#916] opened 2022-07-29 02:33 UTC
Folks on @elastic/infra-monitoring-ui have been doing package dev recently and it seems a number of us are getting duplicate entries for the recently added experimental platform_observability package: https://github.com/elastic/integrations/tree/main/packages/platform_observability

![Pasted_Image_2022_07_29_11_34](https://user-images.githubusercontent.com/690/181670922-abc75784-c637-483b-b490-3cb5db1dcc2d.png)

This persisted for me even after a `elastic-package stack down` and a full docker desktop clean/purge, so I guess it's something coming from the local working dir?

**Comment by jsoriano** [comment] 2022-07-29 07:49
I have transferred the issue to elastic-package as this seems to happen in the context of this tool.

**Comment by jen-huang** [comment] 2022-08-02 00:04
> This would explain duplications, but I don't know why more than two packages can appear there. Maybe @elastic/fleet team can help on this.

Without being able to see the response from the registry, I can't say for certain other than possibly the `policy_templates` field was also getting duplicated for each instance of the package.

I just checked with snapshot EPR (it is on v1.11) and it seems resolved.

**Comment by jsoriano** [comment] 2022-08-02 08:25
@jen-huang thanks!

@matschaffer were you adding `policy_templates` in this package? Are you able to reproduce the issue with current versions of `elastic-package` and the registry?

I am going to close this one as it seems to be fixed by package registry 1.11, please reopen if the issue persist.

**Closed by jsoriano** 2022-08-02 08:25 UTC
Labels: Team:Ecosystem

**Comment by matschaffer** [comment] 2022-08-15 01:10
@jsoriano 

> were you adding policy_templates in this package?

pretty sure yes https://github.com/elastic/integrations/blob/main/packages/platform_observability/manifest.yml#L17 (cc @crespocarlos)

> Are you able to reproduce the issue with current versions of elastic-package and the registry?

I'm just back from PTO today, but I can reopen if I see it again.

**Comment by matschaffer** [comment] 2022-08-15 02:35
I tried a few cycles of `elastic-package build; elastic-package stack up -v -d --services package-registry` from the `platform_observability` package. No idea if this is what might have caused the previous duplicates, but they didn't appear on a fresh stack.
